# Generated by Django 4.0.3 on 2022-04-19 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='blog/images')),
                ('title', models.CharField(default='', max_length=500)),
                ('category', models.CharField(choices=[('mental health', 'mental health'), ('heart disease', 'heart disease'), ('covid19', 'covid19'), ('immunization', 'immunization')], max_length=13)),
                ('summary', models.TextField(max_length=500)),
                ('content', models.TextField(max_length=500000)),
                ('is_draft', models.CharField(choices=[('true', True), ('false', False)], max_length=5)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.CharField(default='', max_length=500)),
                ('category', models.CharField(choices=[('mental health', 'mental health'), ('heart disease', 'heart disease'), ('covid19', 'covid19'), ('immunization', 'immunization')], max_length=13)),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.account')),
            ],
        ),
    ]
