# Generated by Django 4.0.3 on 2022-04-19 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 10, 7, 4, 202678)),
        ),
    ]
