# Generated by Django 4.0.3 on 2022-04-19 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0002_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 11, 7, 55, 227512)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 10, 22, 55, 227512)),
        ),
    ]
